backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "./static/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "business" # Used in routes, e.g., /admin/collections/blog
    label: "Business" # Used in the UI
    folder: "content/business" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Business Name", name: "title", widget: "string"}
      - {label: "Owner Name", name: "ownerName", widget: "string"}
      - {label: "Area of Business", name: "type", widget: "select", options: ['Musician/Performer/Artist', 'Barber/Stylist', 'Graphic Design', 'Photography', 'Healthcare Provider', 'Market/Grocer', 'Educator/Consultant', 'Restaurant/Coffee Shop/Bar', 'Retail', 'Trades', 'Other']}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Phone Number", name: "phoneNumber", widget: "number", required: false}
      - {label: "Location", name: "location", widget: "string", required: false}

      - {label: "Website", name: "website", widget: "string", required: false}
      - {label: "Facebook", name: "facebook", widget: "string", required: false}
      - {label: "Instagram", name: "instagram", widget: "string", required: false}


      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Publish Date", name: "date", widget: "hidden", default: "datetime"}